[package]
name = "kbl"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
clipboard = "0.5.0"
chrono = "0.4.39"
unicode-segmentation = "1.8"
windows = { version = "0.58.0" ,features = ["Win32_Foundation", "Win32_Security","Win32_UI_Input","Win32_UI_WindowsAndMessaging","Win32_UI_Input_KeyboardAndMouse","Win32_System_Threading"]}

[[bin]]
name = "kbl"
subsystem = "windows"
