[package]
name = "kbl"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
clipboard = "0.5.0"
chrono = "0.4.39"
unicode-segmentation = "1.8"

[[bin]]
name = "kbl"
subsystem = "windows"