name: Build Windows .exe

# 触发条件，可以根据需要调整
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Rust 环境
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          default: true

      # 安装目标平台工具链（如果需要）
      - name: Install target
        run: rustup target add x86_64-pc-windows-gnu

      # 编译项目
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      # 打包可执行文件（根据项目结构调整路径）
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp target/x86_64-pc-windows-gnu/release/kbl.exe release/

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: release/kbl.exe
